name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Build
      run: dotnet build ShandyGeckoLogger/ShandyGeckoLogger.csproj --configuration Release
    - name: Test
      run: dotnet test ShandyGeckoLogger.UnitTests/ShandyGeckoLogger.UnitTests.csproj --verbosity normal
    - name: Build solution and generate NuGet package
      run: |  
        cd ShandyGeckoLogger
        dotnet pack -c Release -o out  
    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./ShandyGeckoLogger/ShandyGeckoLogger/out/*.nupkg --skip-duplicate --no-symbols true
